name: Test GCD Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gcd-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Make scripts executable
        run: chmod +x gcd.sh test_gcd.sh

      - name: Run tests
        run: ./test_gcd.sh
